runtime: python311
entrypoint: gunicorn -b :$PORT Flask_app:app

env_variables:
  FLASK_ENV: 'production'
  SECRET_KEY: '4565'

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
